### ISSUE TITLE
Ugly styling, inconsistent with rest of guide

### ISSUE THREAD

**Issue by svgeesus** [w3c/documentreview#10]
It would be better to use the [same style as the rest of the guide](https://github.com/w3c/Guide/blob/master/assets/main.css) rather than the current, ugly styling which makes the document look like something written in 1996.

Unless there are specific objections, I would like to copy over that style. Or link it, so that it always has the same style as the rest of the guide.

**Comment by svgeesus** [comment]
Specifically, to add &lt;link rel="stylesheet" type="text/css" href="https://www.w3.org/Guide/assets/main.css">

**Comment by r12a** [comment]
hi Chris. The styling was minimal and TBD, so it would be good to add styling. However, i've always found the Guide styling difficult to read (and it looks to me like it was developed in 1998), so i'm not too happy to apply it to this page.  I find the text very small

I didn't link to a webfont, but in the previous style sheet i used Raleway as the base font - because it's much easier to read and recommended by the WAI folks.  We have a webfont at https://www.w3.org/International/style/fonts/raleway-regular-webfont.woff2 which you can see in action at https://www.w3.org/International/articles/definitions-characters/ Do you think we should add that as the default font for the Guide?

I find the style you applied way too small and dense to read easily.

And also, the TOC is now broken badly.

**Comment by r12a** [comment]
So, yes, i'm objecting.  Although i'm actually proposing that we refresh the (to me, ugly) style used for the whole Guide, rather than just fix this page (though i'd be happy to do the latter if the former requires turning of the kind that brings to mind a large ship – btw, the Guide already links to many pages that don't use the same style sheet.)

**Comment by svgeesus** [comment]
I see what you mean about the TOC. The text is super small there. It is fine everywhere else. Are you seeing small text everywhere?

I find the Guide styling to be _much better_ in general though.

If you want to either change the Guide styling, or propose a new styling, I guess you would [open an issue over there](https://github.com/w3c/Guide/issues). Proposing Raleway would be fine, it looks nice to me. Although [the page you cite](https://www.w3.org/International/articles/definitions-characters/) has very low contrast, I doubt it would pass WCAG AA.

**Comment by r12a** [comment]
> Are you seeing small text everywhere?

Here's what i see.  I find myself struggling to read it, and can feel the strain on my eyes.

![Screenshot 2020-10-06 at 08 49 18](https://user-images.githubusercontent.com/4839211/95173727-fc17f880-07b0-11eb-8ffd-948a17afb132.png)

Even without changing the font size, this is much more readable if we change the font to Raleway.

![Screenshot 2020-10-06 at 08 50 00](https://user-images.githubusercontent.com/4839211/95173821-1d78e480-07b1-11eb-95d2-c68d167e8d0c.png)

> I find the Guide styling to be much better in general though.

I imagine that's also affected by what one has set as the default font in one's browser.

> Although the page you cite has very low contrast, I doubt it would pass WCAG AA.

Grr. I tried to fix this already.  Looks like i need to do more.  Are you on Windows?

**Comment by r12a** [comment]
wrt the last point, https://webaim.org/resources/contrastchecker/ tells me that it does pass WCAG AA.

**Comment by svgeesus** [comment]
I'm not seeing what you are seeing, @r12a (the screenshot below is shrunk to the width of the comment box, so please view it directly)

![image](https://user-images.githubusercontent.com/2506926/95459906-e9521f00-097c-11eb-8842-e4f2a86f56fd.png)
